project_id = "lkwvlzcapuptcxvwukcm"

[functions.youtube-videos]
verify_jwt = false

[functions.export-metrics]
verify_jwt = false

[functions.create-pix-charge]
verify_jwt = false

[functions.create-vip-charge]
verify_jwt = false

[functions.save-app-config]
verify_jwt = false

[functions.super-admin-metrics]
verify_jwt = false

[functions.youtube-channel-metrics]

[functions.cleanup-expired-stores]
verify_jwt = false

[functions.platform-subscription-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.affiliate-validate]
verify_jwt = false
