project_id = "lkwvlzcapuptcxvwukcm"

[functions.create-pix-charge]
verify_jwt = false

[functions.openpix-webhook]
verify_jwt = false

[functions.youtube-videos]
verify_jwt = false

[functions.mock-pix-webhook]
verify_jwt = false

[functions.sandbox-pix-test]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.manage-subaccount]
verify_jwt = false
